# Generated by Django 5.2.12 on 2026-09-27 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_sequencecounter_order_display_order_id_supportquery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='productimage',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_type',
            field=models.CharField(choices=[('Primary', 'Primary'), ('Gallery', 'Gallery'), ('Lifestyle', 'Lifestyle'), ('Shade Swatch', 'Shade Swatch'), ('Ingredients', 'Ingredients'), ('How To Use', 'How To Use'), ('Texture', 'Texture'), ('Packaging', 'Packaging')], default='Gallery', max_length=50),
        ),
        migrations.AddField(
            model_name='variant',
            name='pack_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='shade_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='shade_family',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='shade_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='shade_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='volume',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.productattribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='dash.product')),
            ],
        ),
    ]
